# ビルド、プッシュ、デプロイのステップを定義
steps:
  # Step 1: Dockerイメージをビルド
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-docker-image'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast1-docker.pkg.dev/whisky-ai-project/whisky-ai-repo/whisky-line-bot-multi-agent:v1.0'
      - '.'

  # Step 2: DockerイメージをArtifact Registryにプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-docker-image'
    args:
      - 'push'
      - 'asia-northeast1-docker.pkg.dev/whisky-ai-project/whisky-ai-repo/whisky-line-bot-multi-agent:v1.0'

  # Step 3: Cloud Runサービスにデプロイ (環境変数を設定)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'whisky-line-bot'
      - '--image'
      - 'asia-northeast1-docker.pkg.dev/whisky-ai-project/whisky-ai-repo/whisky-line-bot-multi-agent:v1.0'
      - '--region'
      - 'asia-northeast1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--memory'
      - '1Gi'
      - '--cpu'
      - '1'
      - '--timeout'
      - '300s'
      - '--max-instances'
      - '10'

      # 【現在有効】Vertex AI を使う場合 (`true`)
      # GOOGLE_CLOUD_PROJECT と GOOGLE_CLOUD_LOCATION を設定します。
      - '--update-env-vars=GOOGLE_GENAI_USE_VERTEXAI=true,GOOGLE_API_KEY=$_GOOGLE_API_KEY,GOOGLE_CLOUD_PROJECT=$PROJECT_ID,GOOGLE_CLOUD_LOCATION=$LOCATION,LINE_CHANNEL_ACCESS_TOKEN=$_LINE_CHANNEL_ACCESS_TOKEN,LINE_CHANNEL_SECRET=$_LINE_CHANNEL_SECRET'

      # 【無効】Google AI Studio を使う場合 (`false`)
      # GOOGLE_CLOUD_PROJECT と GOOGLE_CLOUD_LOCATION は不要なので含めません。
      # - '--update-env-vars=GOOGLE_GENAI_USE_VERTEXAI=false,GOOGLE_API_KEY=$_GOOGLE_API_KEY,LINE_CHANNEL_ACCESS_TOKEN=$_LINE_CHANNEL_ACCESS_TOKEN,LINE_CHANNEL_SECRET=$_LINE_CHANNEL_SECRET'


# ビルドとデプロイに使用するイメージを明記
images:
  - 'asia-northeast1-docker.pkg.dev/whisky-ai-project/whisky-ai-repo/whisky-line-bot-multi-agent:v1.0'

# タイムアウト設定
timeout: '1200s'

# ログの保存設定
options:
  logging: CLOUD_LOGGING_ONLY
